language: java
jdk:
  - oraclejdk8
script: ./build.sh --settings .maven-settings.xml
before_deploy:
  - export RELEASE_JAR_FILE=$(ls target/vlo-mapping-*.jar)
  - echo "Deploying $RELEASE_JAR_FILE (if tag)"
deploy:
  provider: releases
  api_key:
    secure: "$DEPLOY_OAUTH_TOKEN"
  file_glob: true
  file: ${RELEASE_JAR_FILE}
  on:
    tags: true
